# Generated by Django 3.2.11 on 2023-01-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0003_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(),
        ),
    ]
