# Generated by Django 3.2.11 on 2023-01-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0005_auto_20230113_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_type',
            field=models.CharField(choices=[('AD', 'Addition'), ('SU', 'SU'), ('CO', 'Count')], default='AD', max_length=2),
        ),
    ]
