# Generated by Django 3.2.11 on 2023-01-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0006_alter_list_list_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_type',
            field=models.CharField(choices=[('AD', 'Addition'), ('SU', 'Subtraction'), ('CO', 'Count')], default='AD', max_length=2),
        ),
    ]
