# Generated by Django 3.2.11 on 2023-01-14 10:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0008_item_listitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='item',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='stocklist.item'),
        ),
    ]
