# Generated by Django 3.2.11 on 2023-01-14 11:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0010_auto_20230114_1030'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('annotated_items', django.db.models.manager.Manager()),
            ],
        ),
    ]
