# Generated by Django 3.2.11 on 2023-01-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0011_alter_item_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
    ]
