# Generated by Django 3.2.11 on 2023-01-14 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0012_alter_item_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
