# Generated by Django 3.2.11 on 2023-01-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0016_auto_20230114_1457'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique name'),
        ),
    ]
