# Generated by Django 3.2.11 on 2023-01-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0017_auto_20230114_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_type',
            field=models.CharField(choices=[('AD', 'Addition'), ('SU', 'Subtraction'), ('CO', 'Count')], default='AD', editable=False, max_length=2),
        ),
    ]
