# Generated by Django 3.2.11 on 2023-01-18 09:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0018_alter_list_list_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique name',
        ),
        migrations.AddField(
            model_name='session',
            name='previous_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_session', to='stocklist.session'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100000'))]),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique name store'),
        ),
    ]
