# Generated by Django 3.2.11 on 2023-01-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0019_auto_20230118_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='origin',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
