# Generated by Django 3.2.11 on 2023-01-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0022_auto_20230123_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
