# Generated by Django 3.2.11 on 2023-01-23 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0023_alter_session_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
