# Generated by Django 3.2.11 on 2023-01-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0026_auto_20230125_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='session',
            new_name='store',
        ),
    ]
