# Generated by Django 3.2.11 on 2023-01-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0027_rename_session_list_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='store',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='stocklist.store'),
        ),
    ]
