# Generated by Django 3.2.11 on 2023-01-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0028_alter_list_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='session_lists', to='stocklist.list')),
                ('session', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='session_lists', to='stocklist.session')),
            ],
        ),
    ]
