# Generated by Django 3.2.11 on 2023-01-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0029_sessionlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='owner',
        ),
        migrations.AlterField(
            model_name='sessionlist',
            name='list',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='session_list', to='stocklist.list'),
        ),
    ]
