# Generated by Django 3.2.11 on 2023-01-27 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0031_auto_20230127_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='count_list', to='stocklist.list')),
                ('session', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='count_lists', to='stocklist.session')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='count_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SessionList',
        ),
    ]
