# Generated by Django 3.2.11 on 2023-01-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0034_list_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='start_date',
        ),
    ]
