# Generated by Django 3.2.11 on 2023-01-27 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0035_remove_count_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
