# Generated by Django 3.2.11 on 2023-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0036_alter_count_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='frequency',
            field=models.CharField(choices=[('MO', 'Monthly'), ('WE', 'Weekly'), ('DA', 'Daily')], default='DA', editable=False, max_length=2),
        ),
    ]
