# Generated by Django 3.2.11 on 2023-01-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0038_remove_count_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountList',
            new_name='StockList',
        ),
    ]
