# Generated by Django 3.2.11 on 2023-01-28 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0040_stockperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='list',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='stocklists', to='stocklist.list'),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='stocklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(default=django.utils.timezone.localdate)),
                ('stock_period', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='stocktakes', to='stocklist.stockperiod')),
            ],
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='count',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='stocklists', to='stocklist.stocktake'),
        ),
        migrations.DeleteModel(
            name='Count',
        ),
    ]
