# Generated by Django 3.2.11 on 2023-01-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0042_rename_count_stocklist_stocktake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktake',
            name='end_date',
            field=models.DateField(editable=False),
        ),
    ]
