# Generated by Django 3.2.11 on 2023-01-28 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0043_alter_stocktake_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktake',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='Stocklist', max_length=20),
        ),
    ]
