# Generated by Django 3.2.11 on 2023-01-28 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0045_auto_20230128_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='list',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.localdate, help_text='The date the Items were added to the Store'),
        ),
    ]
