# Generated by Django 3.2.11 on 2023-01-28 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0047_alter_list_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.localdate, help_text='The date items were added/removed from the Store'),
        ),
    ]
