# Generated by Django 3.2.11 on 2023-01-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0048_alter_list_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='list',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='stocklist.list'),
        ),
    ]
