# Generated by Django 3.2.11 on 2023-01-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0049_alter_stocklist_list'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listitem',
            constraint=models.UniqueConstraint(fields=('list', 'item'), name='unique item list'),
        ),
    ]
