# Generated by Django 3.2.11 on 2023-02-05 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0050_listitem_unique item list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktake',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='list',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.localdate, help_text='The date these items were added/removed from the Store.'),
        ),
        migrations.AlterField(
            model_name='stockperiod',
            name='frequency',
            field=models.CharField(choices=[('MO', 'Monthly'), ('WE', 'Weekly'), ('DA', 'Daily')], default='DA', max_length=2),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='stockperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('frequency', 'MO'), ('frequency', 'WE'), _connector='OR'), fields=('store', 'frequency'), name='unique monthly_weekly_frequency store'),
        ),
    ]
