# Generated by Django 3.2.11 on 2023-01-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0050_listitem_unique item list'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('frequency', 'MO')), fields=('store', 'frequency'), name='unique monthly_frequency store'),
        ),
        migrations.AddConstraint(
            model_name='stockperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('frequency', 'WE')), fields=('store', 'frequency'), name='unique weekly_frequency store'),
        ),
    ]
