# Generated by Django 3.2.11 on 2023-01-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0051_auto_20230129_0729'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockperiod',
            name='unique monthly_frequency store',
        ),
        migrations.RemoveConstraint(
            model_name='stockperiod',
            name='unique weekly_frequency store',
        ),
        migrations.AddConstraint(
            model_name='stockperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('frequency', 'MO')), fields=('store', 'frequency'), name='unique monthly_frequency store'),
        ),
        migrations.AddConstraint(
            model_name='stockperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('frequency', 'WE')), fields=('store', 'frequency'), name='unique weekly_frequency store'),
        ),
    ]
