# Generated by Django 3.1.7 on 2023-11-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0052_auto_20230726_1012'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='stockperiod',
        #     name='store',
        # ),
        migrations.RemoveField(
            model_name='stocktake',
            name='stock_period',
        ),
        migrations.DeleteModel(
            name='StockList',
        ),
        migrations.DeleteModel(
            name='StockPeriod',
        ),
        migrations.DeleteModel(
            name='Stocktake',
        ),
    ]
