# Generated by Django 3.2.11 on 2023-01-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0052_alter_stockperiod_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockperiod',
            name='frequency',
            field=models.CharField(choices=[('MO', 'Monthly'), ('WE', 'Weekly'), ('DA', 'Daily')], default='DA', editable=False, max_length=2),
        ),
    ]
