# Generated by Django 3.2.11 on 2023-01-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0052_auto_20230129_0731'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.UniqueConstraint(condition=models.Q(('stock_period__frequency', 'MO')), fields=('stock_period', 'end_date'), name='unique end_date monthly_frequency stock_period'),
        ),
    ]
