# Generated by Django 3.2.11 on 2023-01-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0053_stocktake_unique end_date monthly_frequency stock_period'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stocktake',
            name='unique end_date monthly_frequency stock_period',
        ),
    ]
