# Generated by Django 3.1.7 on 2023-11-16 03:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0053_auto_20231114_0128'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listitem',
            name='unique item list',
        ),
        migrations.AlterField(
            model_name='listitem',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100000'))]),
        ),
    ]
