# Generated by Django 3.1.7 on 2023-12-20 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0054_auto_20231116_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date these items were added/removed from the Store.'),
        ),
    ]
