# Generated by Django 3.2.11 on 2023-01-30 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0054_alter_stockperiod_frequency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockperiod',
            name='unique monthly_frequency store',
        ),
        migrations.RemoveConstraint(
            model_name='stockperiod',
            name='unique weekly_frequency store',
        ),
        migrations.AlterField(
            model_name='list',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.localdate, help_text='The date items were added/removed from the Store.'),
        ),
        migrations.AddConstraint(
            model_name='stockperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('frequency', 'MO'), ('frequency', 'WE'), _connector='OR'), fields=('store', 'frequency'), name='unique monthly_frequency store'),
        ),
    ]
