# Generated by Django 3.2.11 on 2023-01-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0055_auto_20230130_0810'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockperiod',
            name='unique monthly_frequency store',
        ),
        migrations.AddConstraint(
            model_name='stockperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('frequency', 'MO'), ('frequency', 'WE'), _connector='OR'), fields=('store', 'frequency'), name='unique monthly_weekly_frequency store'),
        ),
    ]
