# Generated by Django 3.2.11 on 2023-01-31 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0056_auto_20230130_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktake',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='list',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.localdate, help_text='The date these items were added/removed from the Store.'),
        ),
    ]
