# Generated by Django 3.1.7 on 2023-12-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0056_auto_20231228_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.CharField(choices=[('AD', 'Addition'), ('SU', 'Subtraction'), ('CO', 'Count')], default='CO', editable=False, max_length=2),
        ),
    ]
