# Generated by Django 3.1.7 on 2024-01-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0057_auto_20231231_1507'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listitem',
            constraint=models.UniqueConstraint(fields=('list', 'item'), name='unique list item'),
        ),
    ]
