# Generated by Django 3.2.11 on 2024-01-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0059_auto_20240108_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, help_text='The date these items were added/removed from the Store.'),
        ),
    ]
